backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
site_url: https://ingress.netlify.app/
publish_mode: editorial_workflow
local: "de"
collections:
  - name: 'cycle' # Used in routes, e.g., /admin/collections/blog
    label: 'Cycles' # Used in the UI
    label_singular: 'Cycle'
    folder: 'src/cycles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: 'md'
    editor:
      preview: false
    summary: 'Cycle {{cycle}}/{{cycleYear}} | RES: {{resistance}} ENL: {{enlightened}} '
    slug: '{{year}}-{{cycle}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'cell', name: 'cell', widget: 'hidden', default: 'NR02-GOLF-04' }
      - { label: 'year', name: 'cycleYear', widget: 'number' }
      - { label: 'cycle', name: 'cycle', widget: 'number' }
      - { label: 'Resistance', name: 'resistance', widget: 'string' }
      - { label: 'Enlightened', name: 'enlightened', widget: 'string' }
      - { label: 'STIREP', name: 'body', required: false, widget: 'markdown' }
      - { label: 'Featured Image', required: false, name: 'thumbnail', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
